### PR TITLE
replaced raw JS with Jquery

### PR DESCRIPTION
**Pull request by abrarShariar**
Code is clean and short. Since Jquery has its own built-in **Ajax**  methods so I replaced the native JS code with Jquery. Hopefully Code is more readable and short.

### CODE REVIEW

**Comment by ehzawad** [comment]
Thank you @abrarShariar ...I did not work with JQuery yet....

**Comment by ehzawad** [comment]
@abrarShariar Please keep gh-pages in sync with master branch...

**Comment by abrarShariar** [comment]
if i fork a repo and then if the owner's gh-pages is updated than do i have to sync it with mine as well ?? isnt my forked version supposed to get synced with owner's commit automatically ??

**Comment by ehzawad** [comment]
Yeah synced automatically...But for this repo we need to change only gh-pages....It can be possible gh-pages branches as a default branch though(Deleting master branch)..

**Comment by abrarShariar** [comment]
Ok,so i have to set the default branch to gh-pages for my repo now ? right ??

**Comment by ehzawad** [comment]
You can do but not needed really...

You can sync local git repo in your machine executing following command..

git checkout gh-pages // go to the gh-pages branch
git rebase master // bring gh-pages up to date with master
git push origin gh-pages // commit the changes
git checkout master // return to the master branch

**Pull request merged**
